/**
 * Pipeline Health — is the kundali write path actually working right now?
 *
 * Built after a three-day outage nobody noticed: on 2026-08-18 the RLS hardening
 * in migrations 012/013 broke guest saves (INSERT ... RETURNING hit SELECT
 * policies that no guest row matched). Guest volume went 12 -> 3 -> 0 -> 0 -> 0
 * while signed-in volume held at ~30/day, so every aggregate number stayed green
 * and the panel's empty list was indistinguishable from a quiet day.
 *
 * Hence the three design rules here:
 *   1. Report each stream separately. Never a combined total.
 *   2. Never render a zero where the truth is "the request failed".
 *   3. Give the operator a way to test the write path directly (the canary),
 *      instead of inferring health from an absence of rows.
 *
 * Data comes through the admin edge function (service role). Direct browser
 * reads of kundli_reports are RLS-gated and were the original source of the
 * "looks empty, is actually blocked" confusion.
 */

import { useState, useEffect, useCallback } from "react";
import {
  Activity, AlertTriangle, RefreshCw, ChevronDown, ChevronUp,
  ShieldCheck, FlaskConical, Check, X, Loader2,
} from "lucide-react";
import {
  ResponsiveContainer, BarChart, Bar, XAxis, YAxis, Tooltip, CartesianGrid, Legend,
} from "recharts";
import { createClient } from "@supabase/supabase-js";
import { supabase } from "@/lib/supabase";
import { useAdminTheme } from "@/lib/admin-theme-context";
import { Pill } from "./AdminCard";

// ─── Types ──────────────────────────────────────────────────────────────────

type StreamKey = "guest" | "signed_in" | "admin";

interface StreamStats {
  last_at: string | null;
  hours_since: number | null;
  count_24h: number;
  count_7d: number;
  count_prev_7d: number;
  total: number;
}

interface DailyRow {
  day: string;
  guest: number;
  signed_in: number;
  admin: number;
}

interface Health {
  generated_at: string;
  streams: Record<StreamKey, StreamStats>;
  daily: DailyRow[];
}

interface Alert {
  id: string;
  stream: string;
  severity: "warn" | "critical";
  message: string;
  hours_since: number | null;
  detected_at: string;
  /** Null while the outage is ongoing; stamped by pipeline_health_check() once
   *  the stream produces a row again. */
  resolved_at: string | null;
}

interface PolicyRow {
  table: string;
  policy: string;
  cmd: string;
  roles: string;
  qual: string | null;
  with_check: string | null;
}

// ─── Config ─────────────────────────────────────────────────────────────────

/**
 * Mirrors pipeline_thresholds in migration 015. Duplicated here only to colour
 * the tiles; the authoritative copy — the one the cron watchdog uses — lives in
 * the database so it can be retuned without a deploy.
 */
const STREAMS: { key: StreamKey; label: string; warnHours: number | null; critHours: number | null }[] = [
  { key: "guest",     label: "Guest",       warnHours: 24, critHours: 72 },
  { key: "signed_in", label: "Signed-in",   warnHours: 12, critHours: 24 },
  // Admin kundalis are generated by hand and are rare — no staleness thresholds,
  // or the tile would sit red permanently and train everyone to ignore it.
  { key: "admin",     label: "Admin-made",  warnHours: null, critHours: null },
];

/**
 * The policies this app depends on. Presence is what the checklist reports; the
 * raw dump below it is for when something is missing and you need the details.
 */
const EXPECTED_POLICIES: { table: string; policy: string; cmd: string; why: string }[] = [
  { table: "kundli_reports", policy: "anyone can insert reports",   cmd: "INSERT", why: "guest + signed-in saves" },
  { table: "kundli_reports", policy: "users read own reports",      cmd: "SELECT", why: "profile history" },
  { table: "kundli_reports", policy: "public read shared reports",  cmd: "SELECT", why: "/shared/:slug links" },
  { table: "kundli_reports", policy: "admins read all reports",     cmd: "SELECT", why: "admin viewing" },
];

// ─── Helpers ────────────────────────────────────────────────────────────────

function relativeAge(hours: number | null): string {
  if (hours === null) return "never";
  if (hours < 1) return `${Math.round(hours * 60)}m ago`;
  if (hours < 48) return `${hours.toFixed(1)}h ago`;
  return `${Math.floor(hours / 24)}d ago`;
}

/** Colour a stream by its own thresholds — a dead stream must read red on its
 *  own, no matter how healthy its neighbours look. That masking is the exact
 *  reason the original outage went unseen.
 *
 *  "nodata" (the stream has never produced a row) is deliberately neutral, not
 *  critical. pipeline_health_check() skips such a stream entirely — `if last_seen
 *  is null then continue` — so painting it red here would put a permanent alarm
 *  on screen with no alert behind it, on every fresh environment. A red that
 *  never means anything teaches people to ignore red, which is the exact habit
 *  this card exists to prevent. The two must agree; the watchdog is right. */
function severityOf(hours: number | null, warn: number | null, crit: number | null): "ok" | "warn" | "crit" | "none" | "nodata" {
  if (hours === null) return "nodata";
  if (warn === null && crit === null) return "none";
  if (crit !== null && hours >= crit) return "crit";
  if (warn !== null && hours >= warn) return "warn";
  return "ok";
}

const SEV_TEXT: Record<string, string> = {
  ok: "text-admin-ok",
  warn: "text-admin-warn",
  crit: "text-admin-danger",
  none: "text-admin-text-secondary",
  nodata: "text-admin-text-faint",
};

const SEV_RING: Record<string, string> = {
  ok: "border-admin-border",
  warn: "border-admin-warn/40",
  crit: "border-admin-danger/40",
  none: "border-admin-border",
  nodata: "border-admin-border border-dashed",
};

/**
 * `monitored` false means this stream has no staleness thresholds (admin-made
 * kundalis are produced by hand and are rare). Such a stream must not be colour-
 * coded: a tile that says "not monitored" in gray above a red "-100% vs prior 7d"
 * is telling the operator two opposite things at once, and the red one is not
 * actionable. The number still shows — just neutrally.
 */
function deltaLabel(cur: number, prev: number, monitored: boolean): { text: string; cls: string } {
  const neutral = "text-admin-text-faint";
  if (prev === 0 && cur === 0) return { text: "—", cls: neutral };
  if (prev === 0) return { text: `+${cur} new`, cls: monitored ? "text-admin-ok" : neutral };
  const pct = Math.round(((cur - prev) / prev) * 100);
  const sign = pct > 0 ? "+" : "";
  const text = `${sign}${pct}% vs prior 7d`;
  if (!monitored) return { text, cls: neutral };
  if (pct <= -60) return { text, cls: "text-admin-danger" };
  if (pct < 0) return { text, cls: "text-admin-warn" };
  return { text, cls: "text-admin-ok" };
}

// ─── Component ──────────────────────────────────────────────────────────────

export function PipelineHealth() {
  // Recharts cannot read Tailwind classes, so the chart palette comes from the
  // theme context as plain hex.
  const { chartColors } = useAdminTheme();
  const [health, setHealth] = useState<Health | null>(null);
  const [alerts, setAlerts] = useState<Alert[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  /** When the alerts on screen were last actually confirmed against the server.
   *  Null until the first successful fetch. */
  const [verifiedAt, setVerifiedAt] = useState<string | null>(null);
  const [showDiagnostics, setShowDiagnostics] = useState(false);

  const fetchHealth = useCallback(async () => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: err } = await supabase.functions.invoke("admin-user-management", {
        body: { action: "pipeline-health" },
      });
      if (err || data?.error) {
        const msg = err?.message || data?.error || "Unknown error";
        console.error("Pipeline health fetch failed:", msg);
        setError(msg);
        setHealth(null);
        // Deliberately keep `alerts` and `verifiedAt`. Clearing them would show a
        // false all-clear for an outage that is probably still happening; leaving
        // them unmarked would present unverified state as current. The banner
        // reads the staleness off `error` and says so instead.
      } else {
        setHealth(data.health as Health);
        setAlerts((data.alerts ?? []) as Alert[]);
        setVerifiedAt(new Date().toISOString());
      }
    } catch (e) {
      const msg = e instanceof Error ? e.message : String(e);
      console.error("Pipeline health fetch failed:", msg);
      setError(msg);
      setHealth(null);
    }
    setLoading(false);
  }, []);

  useEffect(() => { fetchHealth(); }, [fetchHealth]);

  // An alert is "open" until the watchdog stamps resolved_at. Resolved ones are
  // kept and shown as incident history — a self-healing outage that left no trace
  // is indistinguishable from one that never happened.
  const openAlerts = alerts.filter((a) => !a.resolved_at);
  const resolvedAlerts = alerts.filter((a) => a.resolved_at);
  const stale = error !== null && openAlerts.length > 0;

  return (
    <div className="mb-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-4 mb-3">
        <div className="flex items-center gap-2">
          <Activity className="w-4 h-4 text-admin-cyan" />
          <h2 className="text-sm font-semibold text-admin-text">Pipeline Health</h2>
          {!loading && !error && health && (
            <Pill size="md" tone="bg-admin-surface-2 text-admin-text-muted border border-admin-border">
              as of {new Date(health.generated_at).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}
            </Pill>
          )}
        </div>
        <button
          onClick={fetchHealth}
          disabled={loading}
          className="flex items-center gap-1.5 px-2 min-h-[44px] sm:min-h-0 sm:py-1 text-xs text-admin-text-muted hover:text-admin-text transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </div>

      {/* Alert banner — the whole point of this card. Raised hourly by
          pipeline_health_check(), so it appears whether or not anyone is here. */}
      {openAlerts.length > 0 && (
        <div className="mb-4 space-y-2">
          {stale && (
            <p className="text-[11px] text-admin-text-muted flex items-center gap-1.5">
              <AlertTriangle className="w-3 h-3 shrink-0" />
              Could not refresh: showing the last confirmed state
              {verifiedAt && ` from ${new Date(verifiedAt).toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}`}.
              These may no longer be accurate.
            </p>
          )}
          {openAlerts.map((a) => (
            <div
              key={a.id}
              className={`flex items-start gap-3 px-4 py-3 rounded-xl border ${
                stale ? "opacity-60 border-dashed" : ""
              } ${
                a.severity === "critical"
                  ? "border-admin-danger/40 bg-admin-danger/15 text-admin-danger"
                  : "border-admin-warn/40 bg-admin-warn/15 text-admin-warn"
              }`}
            >
              <AlertTriangle className="w-4 h-4 mt-0.5 shrink-0" />
              <div className="min-w-0">
                <p className="text-sm font-medium">{a.message}</p>
                <p className="text-xs opacity-70 mt-0.5">
                  detected {new Date(a.detected_at).toLocaleString("en-IN")}
                  {stale && " · unverified"}
                </p>
              </div>
            </div>
          ))}
        </div>
      )}

      {/* An error must never be able to look like a healthy zero. */}
      {error ? (
        <div className="rounded-xl border border-admin-danger/40 bg-admin-danger/15 p-6 text-center text-admin-danger text-sm">
          <p className="font-medium mb-1">Could not load pipeline health.</p>
          <p className="text-xs text-admin-danger/80 break-words">{error}</p>
        </div>
      ) : loading && !health ? (
        <div className="rounded-xl border border-admin-border bg-admin-surface p-6 text-center text-admin-text-faint text-sm">
          <Loader2 className="w-4 h-4 animate-spin inline-block mr-2" />
          Loading pipeline health...
        </div>
      ) : health ? (
        <>
          {/* Per-stream tiles */}
          <div className="grid grid-cols-1 sm:grid-cols-3 gap-4 mb-4">
            {STREAMS.map(({ key, label, warnHours, critHours }) => {
              const s = health.streams?.[key];
              const sev = severityOf(s?.hours_since ?? null, warnHours, critHours);
              const monitored = sev !== "none" && sev !== "nodata";
              const delta = deltaLabel(s?.count_7d ?? 0, s?.count_prev_7d ?? 0, monitored);
              return (
                <div key={key} className={`bg-admin-surface border rounded-xl p-4 ${SEV_RING[sev]}`}>
                  <div className="flex items-center justify-between gap-2">
                    <p className="text-xs text-admin-text-muted">{label}</p>
                    {sev === "crit" && <Pill tone="bg-admin-danger/20 text-admin-danger" className="px-1.5">stale</Pill>}
                    {sev === "warn" && <Pill tone="bg-admin-warn/20 text-admin-warn" className="px-1.5">quiet</Pill>}
                    {sev === "nodata" && <Pill tone="bg-admin-surface-3/40 text-admin-text-muted" className="px-1.5">no data</Pill>}
                    {sev === "none" && <Pill tone="bg-admin-surface-3/40 text-admin-text-muted" className="px-1.5">not monitored</Pill>}
                  </div>
                  <p className={`text-2xl font-bold mt-1 ${SEV_TEXT[sev]}`}>
                    {relativeAge(s?.hours_since ?? null)}
                  </p>
                  <p className="text-xs text-admin-text-faint mt-1">
                    {s?.count_24h ?? 0} in 24h · {s?.count_7d ?? 0} in 7d · {s?.total ?? 0} total
                  </p>
                  <p className={`text-[11px] mt-1 ${delta.cls}`}>{delta.text}</p>
                </div>
              );
            })}
          </div>

          {/* 30-day trend — a cliff in one stream is obvious here even while the
              others carry on, which is exactly what a stacked total would hide. */}
          <div className="rounded-xl border border-admin-border bg-admin-surface p-4 mb-4">
            <p className="text-xs text-admin-text-muted mb-3">Kundalis saved per day (30 days)</p>
            <div className="h-48">
              <ResponsiveContainer width="100%" height="100%">
                <BarChart data={health.daily} margin={{ top: 4, right: 4, bottom: 0, left: -20 }}>
                  <CartesianGrid strokeDasharray="3 3" stroke={chartColors.grid} vertical={false} />
                  <XAxis
                    dataKey="day"
                    tick={{ fill: chartColors.tick, fontSize: 10 }}
                    tickFormatter={(d: string) => d.slice(5)}
                    interval="preserveStartEnd"
                    minTickGap={24}
                    axisLine={{ stroke: chartColors.axis }}
                    tickLine={false}
                  />
                  <YAxis
                    tick={{ fill: chartColors.tick, fontSize: 10 }}
                    allowDecimals={false}
                    axisLine={false}
                    tickLine={false}
                  />
                  <Tooltip
                    contentStyle={{
                      background: chartColors.tooltipBg,
                      border: `1px solid ${chartColors.tooltipBorder}`,
                      borderRadius: 8,
                      fontSize: 12,
                    }}
                    labelStyle={{ color: chartColors.legend }}
                  />
                  <Legend wrapperStyle={{ fontSize: 11, color: chartColors.legend }} />
                  {STREAMS.map(({ key, label }) => (
                    <Bar key={key} dataKey={key} name={label} stackId="a" fill={chartColors[key]} />
                  ))}
                </BarChart>
              </ResponsiveContainer>
            </div>
          </div>
        </>
      ) : null}

      {/* Incident history — outages that already recovered. Without this, a break
          at 02:00 that self-healed by 08:00 leaves a spotless panel by the time
          anyone looks, so a repeating intermittent fault stays invisible. */}
      {resolvedAlerts.length > 0 && (
        <div className="rounded-xl border border-admin-border bg-admin-surface p-4 mb-4">
          <p className="text-xs text-admin-text-muted mb-2">
            Resolved incidents · last 14 days
          </p>
          <div className="space-y-1.5">
            {resolvedAlerts.map((a) => {
              const start = new Date(a.detected_at);
              const end = new Date(a.resolved_at as string);
              const mins = Math.max(0, Math.round((end.getTime() - start.getTime()) / 60000));
              const duration = mins < 60 ? `${mins}m` : `${(mins / 60).toFixed(1)}h`;
              return (
                <div key={a.id} className="flex items-center gap-2 text-[11px] flex-wrap">
                  <Check className="w-3 h-3 text-admin-ok shrink-0" />
                  <span className={a.severity === "critical" ? "text-admin-danger/80" : "text-admin-warn/80"}>
                    {a.stream}
                  </span>
                  <span className="text-admin-text-faint">down {duration}</span>
                  <span className="text-admin-text-faint">·</span>
                  <span className="text-admin-text-faint">
                    {start.toLocaleString("en-IN", { day: "numeric", month: "short", hour: "2-digit", minute: "2-digit" })}
                    {" → "}
                    {end.toLocaleTimeString("en-IN", { hour: "2-digit", minute: "2-digit" })}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      )}

      {/* Diagnostics */}
      <button
        onClick={() => setShowDiagnostics((v) => !v)}
        className="w-full flex items-center justify-between gap-4 px-4 min-h-[44px] py-2.5 rounded-xl border border-admin-border bg-admin-surface hover:bg-admin-surface-2/60 transition-colors"
      >
        <span className="flex items-center gap-2 text-xs text-admin-text-secondary">
          <FlaskConical className="w-3.5 h-3.5 text-admin-cyan" />
          Write canary &amp; RLS snapshot
        </span>
        {showDiagnostics
          ? <ChevronUp className="w-4 h-4 text-admin-text-muted" />
          : <ChevronDown className="w-4 h-4 text-admin-text-muted" />}
      </button>

      {showDiagnostics && (
        <div className="mt-3 space-y-3">
          <WriteCanary />
          <RlsSnapshot />
        </div>
      )}
    </div>
  );
}

// ─── Write canary ───────────────────────────────────────────────────────────

/**
 * Exercises the real guest write path end to end: an anonymous insert into
 * kundli_reports, then a service-role delete that confirms the row actually
 * landed. Run it after any migration that touches RLS.
 *
 * It must run as anon, not as the signed-in admin — the admin's own JWT matches
 * policies a guest does not, which is precisely how the original breakage stayed
 * invisible to everyone testing while logged in.
 */
function WriteCanary() {
  const [running, setRunning] = useState(false);
  const [result, setResult] = useState<{ ok: boolean; detail: string } | null>(null);

  const run = async () => {
    setRunning(true);
    setResult(null);

    const sessionId = `canary-${crypto.randomUUID()}`;

    try {
      // Built lazily and with its own storageKey: a second client sharing the
      // default key races the admin's live session in localStorage and can log
      // them out. persistSession:false means no shared storage and no refresh
      // timer, so this instance cannot touch the real session.
      const anon = createClient(
        import.meta.env.VITE_SUPABASE_URL as string,
        import.meta.env.VITE_SUPABASE_ANON_KEY as string,
        {
          auth: {
            persistSession: false,
            autoRefreshToken: false,
            detectSessionInUrl: false,
            storageKey: "sb-canary",
          },
        },
      );

      // Mirrors saveKundaliReport() exactly, including the absence of .select().
      // Adding .select() here would make this an INSERT ... RETURNING and
      // reproduce the original bug — which is the point: it should fail if the
      // policies regress.
      const { error } = await anon.from("kundli_reports").insert({
        id: crypto.randomUUID(),
        user_id: null,
        session_id: sessionId,
        // A UUID, not Math.random(): share_slug is UNIQUE, and a collision would
        // surface as a rejected insert — indistinguishable from the RLS
        // regression this probe exists to detect. A diagnostic must not have a
        // false-alarm path.
        share_slug: `canary-${crypto.randomUUID()}`,
        full_name: "__canary__",
        birth_date: "1990-01-01",
        birth_time: "12:00",
        birth_place: "Canary Probe",
      });

      if (error) {
        // 23505 is a unique-constraint violation, not a permissions problem.
        // Calling that an RLS failure would send someone auditing policies over
        // a slug clash, so name it for what it is.
        const isDuplicate = error.code === "23505";
        setResult({
          ok: false,
          detail: isDuplicate
            ? `Probe could not run: duplicate key [23505], ${error.message}. `
              + `This is not an RLS failure; re-run the test.`
            : `Anonymous insert rejected [${error.code ?? "no-code"}]: ${error.message}`,
        });
        setRunning(false);
        return;
      }

      // Deleting is also the assertion: a count of 1 proves the row really
      // landed, rather than trusting an error-free response.
      const { data, error: cleanupErr } = await supabase.functions.invoke("admin-user-management", {
        body: { action: "canary-cleanup", sessionId },
      });

      if (cleanupErr || data?.error) {
        setResult({
          ok: false,
          detail: `Insert succeeded but cleanup failed: ${cleanupErr?.message || data?.error}. `
                + `The hourly job will sweep it.`,
        });
      } else if (data?.deleted === 1) {
        setResult({ ok: true, detail: "Anonymous insert succeeded, row verified and removed." });
      } else {
        setResult({
          ok: false,
          detail: `Insert reported success but ${data?.deleted ?? 0} rows were found. `
                + `The write is not landing.`,
        });
      }
    } catch (e) {
      setResult({ ok: false, detail: e instanceof Error ? e.message : String(e) });
    }
    setRunning(false);
  };

  return (
    <div className="rounded-xl border border-admin-border bg-admin-surface p-4">
      <div className="flex items-start justify-between gap-4">
        <div className="min-w-0">
          <p className="text-xs font-medium text-admin-text">Guest write canary</p>
          <p className="text-[11px] text-admin-text-faint mt-0.5">
            Inserts a probe row as an anonymous visitor, verifies it landed, deletes it.
            Run after any RLS change.
          </p>
        </div>
        <button
          onClick={run}
          disabled={running}
          className="shrink-0 px-4 min-h-[44px] rounded-lg bg-admin-cyan/20 text-admin-cyan border border-admin-cyan/40 text-xs hover:bg-admin-cyan/30 transition-colors disabled:opacity-50"
        >
          {running ? <Loader2 className="w-3.5 h-3.5 animate-spin inline-block" /> : "Run test"}
        </button>
      </div>

      {result && (
        <div
          className={`mt-3 flex items-start gap-2 px-3 py-2 rounded-lg text-xs ${
            result.ok
              ? "bg-admin-ok/15 border border-admin-ok/40 text-admin-ok"
              : "bg-admin-danger/15 border border-admin-danger/40 text-admin-danger"
          }`}
        >
          {result.ok
            ? <Check className="w-3.5 h-3.5 mt-0.5 shrink-0" />
            : <X className="w-3.5 h-3.5 mt-0.5 shrink-0" />}
          <span className="break-words">{result.detail}</span>
        </div>
      )}
    </div>
  );
}

// ─── RLS snapshot ───────────────────────────────────────────────────────────

/**
 * The live policy map, because the repo's migration files are not the truth —
 * migration 013 found a policy that existed only in the dashboard, and 014 was
 * applied by hand with no record in the repo.
 */
function RlsSnapshot() {
  const [policies, setPolicies] = useState<PolicyRow[] | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [showRaw, setShowRaw] = useState(false);

  const load = async () => {
    setLoading(true);
    setError(null);
    try {
      const { data, error: err } = await supabase.functions.invoke("admin-user-management", {
        body: { action: "rls-snapshot" },
      });
      if (err || data?.error) {
        setError(err?.message || data?.error || "Unknown error");
        setPolicies(null);
      } else {
        setPolicies((data.policies ?? []) as PolicyRow[]);
      }
    } catch (e) {
      setError(e instanceof Error ? e.message : String(e));
      setPolicies(null);
    }
    setLoading(false);
  };

  useEffect(() => { load(); }, []);

  return (
    <div className="rounded-xl border border-admin-border bg-admin-surface p-4">
      <div className="flex items-start justify-between gap-4 mb-3">
        <div className="min-w-0">
          <p className="text-xs font-medium text-admin-text flex items-center gap-1.5">
            <ShieldCheck className="w-3.5 h-3.5 text-admin-cyan" />
            Live RLS policies
          </p>
          <p className="text-[11px] text-admin-text-faint mt-0.5">
            Read from the database, not the migration files.
          </p>
        </div>
        <button
          onClick={load}
          disabled={loading}
          className="shrink-0 flex items-center gap-1.5 px-2 min-h-[44px] sm:min-h-0 text-xs text-admin-text-muted hover:text-admin-text transition-colors"
        >
          <RefreshCw className={`w-3.5 h-3.5 ${loading ? "animate-spin" : ""}`} />
          Refresh
        </button>
      </div>

      {error ? (
        <p className="text-xs text-admin-danger break-words">Could not read policies: {error}</p>
      ) : !policies ? (
        <p className="text-xs text-admin-text-faint">Loading…</p>
      ) : (
        <>
          <div className="space-y-1.5">
            {EXPECTED_POLICIES.map((exp) => {
              const found = policies.some(
                (p) => p.table === exp.table && p.policy === exp.policy && p.cmd === exp.cmd,
              );
              return (
                <div key={`${exp.table}.${exp.policy}`} className="flex items-center gap-2 text-xs">
                  {found
                    ? <Check className="w-3.5 h-3.5 text-admin-ok shrink-0" />
                    : <X className="w-3.5 h-3.5 text-admin-danger shrink-0" />}
                  <span className={found ? "text-admin-text-secondary" : "text-admin-danger font-medium"}>
                    {exp.policy}
                  </span>
                  <span className="text-admin-text-faint">·</span>
                  <span className="text-admin-text-faint">{exp.why}</span>
                </div>
              );
            })}
          </div>

          <button
            onClick={() => setShowRaw((v) => !v)}
            className="mt-3 px-2 min-h-[44px] sm:min-h-0 text-[11px] text-admin-text-faint hover:text-admin-text-secondary transition-colors"
          >
            {showRaw ? "Hide" : "Show"} all {policies.length} policies
          </button>

          {showRaw && (
            <div className="mt-2 overflow-x-auto">
              <table className="w-full text-[11px]">
                <thead>
                  <tr className="text-admin-text-faint uppercase tracking-wider border-b border-admin-border">
                    <th className="px-2 py-1.5 text-left">Table</th>
                    <th className="px-2 py-1.5 text-left">Policy</th>
                    <th className="px-2 py-1.5 text-left">Cmd</th>
                    <th className="px-2 py-1.5 text-left">Using / Check</th>
                  </tr>
                </thead>
                <tbody>
                  {policies.map((p) => (
                    <tr key={`${p.table}.${p.policy}.${p.cmd}`} className="border-t border-admin-border-subtle">
                      <td className="px-2 py-1.5 text-admin-text-muted whitespace-nowrap">{p.table}</td>
                      <td className="px-2 py-1.5 text-admin-text">{p.policy}</td>
                      <td className="px-2 py-1.5 text-admin-text-muted">{p.cmd}</td>
                      <td className="px-2 py-1.5 text-admin-text-faint font-mono break-all">
                        {p.qual ?? p.with_check ?? "—"}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          )}
        </>
      )}
    </div>
  );
}
